### ISSUE TITLE
Input folder duplication on output

### ISSUE THREAD

**Issue by xirzec** [sandersn/downlevel-dts#11]
I have a project that puts typings into a folder like:

```
\typings\latest\src\foo.d.ts
\typings\latest\test\bar.d.ts
```

I try running downlevel-dts against this folder like so `npx downlevel-dts typings\latest typings\3.4`

I end up with a `typings\3.4` folder, but besides having `src` and `test`, it also has a path that looks like the path in my monorepo down to where my package.json is (with some of the beginning chopped off):

`typings\3.4\dk-for-js\sdk\storage\storage\blob\typings\latest\...`

**Comment by sandersn** [comment]
Is there anything in that directory? I tried to repro this and so far have not been able to. Can you point me to your repo?

**Comment by xirzec** [comment]
Yeah, it seems to have a full copy of the typings. 

The fastest (but certainly not the cleanest) repro I can give is:

1. `git clone https://github.com/xirzec/azure-sdk-for-js.git`
2. `cd azure-sdk-for-js`
3. `git checkout updateTS37`
4. `npm install -g @microsoft/rush` (sorry, we're a monorepo and have private packages)
5. `rush update`
6. `rush build -t @azure/storage-blob`
7. `cd sdk\storage\storage-blob`
8. `npm run build:types`

At this point you can look in the `typings` folder and see a `3.4` folder that contains the weird partial path folder:

```
c:\src\temp\azure-sdk-for-js\sdk\storage\storage-blob>dir typings\3.4
 Volume in drive C is OSDisk
 Volume Serial Number is 0A17-7DAE

 Directory of c:\src\temp\azure-sdk-for-js\sdk\storage\storage-blob\typings\3.4

01/16/2020  04:16 PM    <DIR>          .
01/16/2020  04:16 PM    <DIR>          ..
01/16/2020  04:16 PM    <DIR>          src
01/16/2020  04:16 PM           377,468 storage-blob.d.ts
01/16/2020  04:16 PM    <DIR>          test
01/16/2020  04:16 PM    <DIR>          ure-sdk-for-js
```

**Comment by sandersn** [comment]
Thanks, I got the repro working from your instructions.
