### ISSUE TITLE
Reference types directives appear to be duplicated

### ISSUE THREAD

**Issue by xirzec** [sandersn/downlevel-dts#12]
If an input d.ts has a reference directive like
```ts
/// <reference types="node" />
```

then that line will appear twice in the output d.ts:

```ts
/// <reference types="node" />
/// <reference types="node" />
```

**Comment by sandersn** [comment]
Repros for me, but only as the first line of the file. Probably I'm doing something subtly wrong with printing the source file.

**Comment by sandersn** [comment]
Filed https://github.com/microsoft/TypeScript/issues/36242 to track this since it appears to be a bug in Typescript itself. In the meantime I'll look for a workaround.
