### ISSUE TITLE
Downlevel "as const"

### ISSUE THREAD

**Issue by southpolesteve** [sandersn/downlevel-dts#2]
`as const` released in 3.4 makes dealing with constant strings and numbers much easier for library authors. Unfortunately, we have not been able to adopt it and also support typescript <3.4 users. It would be great if this could support down leveling `as const`. 

Currently, I end up doing [something like this ](https://github.com/Azure/azure-sdk-for-js/blob/f4f353dba83783213b09db20271f2aac90af3e68/sdk/cosmosdb/cosmos/src/request/StatusCodes.ts#L6-L12). Enums are ok for internal usage, but const objects with `as const` are my preference for publicly exported values. It allows users to easily supply literal values where we expect a union of possible values.

**Comment by ajafff** [comment]
This tool is intended to make declaration files generated with a new version of the compiler compatible with older versions of the compiler.
Since `as const` is not a declaration file feature, I doubt that this request will be considered.

**Comment by southpolesteve** [comment]
@ajafff Yep! You are right. I didn't realize `as const` got output to readonly in .d.ts. So nvm. This works fine now.
