### ISSUE TITLE
downlevel template literal types

### ISSUE THREAD

**Issue by Hotell** [sandersn/downlevel-dts#72]
there is missing support for template literal types introduced in [TS 4.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types)

### Current Behaviour

```ts
export declare type Greeting = `hello ${World}`
declare type World = 'world'
```

↓↓↓ `downlevel-dts` ↓↓↓

```ts
export declare type Greeting = `hello ${World}`
declare type World = 'world'
```

### Expected Behaviour

```ts
export declare type Greeting = `hello ${World}`
declare type World = 'world'
```

↓↓↓ `downlevel-dts` ↓↓↓

```ts
// Good enough
export declare type Greeting = string
// This would be awesome
export declare type Greeting = `hello world`
declare type World = 'world'
```

**Comment by JeremyJonas** [comment]
Need this as well. Is anyone working on this?

If no one is working on this, I can likely contribute. I don't see much in terms on contribution/development docs... should this live in the 4.1 baseline or in previous baseline (3.9/4.0)?

Any pointers into how to go about developing this before I spelunker too deep into the code would be great.
