### ISSUE TITLE
Public version of package isn't runnable as a command

### ISSUE THREAD

**Issue by xirzec** [sandersn/downlevel-dts#9]
Something like `npx downlevel-dts . ts3.4` doesn't work at the moment, because the version of the package that is published on NPM doesn't have ` "bin": "index.js",` in its package.json.

Instead you get an error: `command not found: downlevel-dts`

**Comment by sandersn** [comment]
Fixed by #3, I just need to publish a new version.

**Comment by sandersn** [comment]
0.2.0 is now published, and can downlevel new 3.8 features as well.

**Comment by xirzec** [comment]
Thanks for the quick fix! 💯
